### ISSUE TITLE
SyntaxError: invalid character '·' (U+00B7)

### ISSUE THREAD

**Issue by bagolyszkij** [Animator-Anon/Animator#26]
Hey there,
I need a little bit of help here! :)
I installed FFMPEG properly and copied the files to the SCRIPTS folder and always get this message when start web ui:
```

Launching Web UI with arguments:
Error loading script: animator_v3.py
Traceback (most recent call last):
  File "C:\Users\gonzo_tower\Downloads\SD\SUPER SD 2.0\stable-diffusion-webui\modules\scripts.py", line 157, in load_scripts
    compiled = compile(text, scriptfile.path, 'exec')
  File "C:\Users\gonzo_tower\Downloads\SD\SUPER SD 2.0\stable-diffusion-webui\scripts\animator_v3.py", line 70
    <title>Animator/animator_v3.py at main · Animator-Anon/Animator · GitHub</title>
                                           ^
SyntaxError: invalid character '·' (U+00B7)
```

What can be the problem?
Any kind of help would be highly appreciated!
Many thanks,
bagolyszkij

**Comment by Animator-Anon** [comment]
Are you using an old version of v3? That line number doesn't seem to match what's there now. Please pull down the newest one and try again.

**Comment by bagolyszkij** [comment]
Exactly the same issue with v4...

```
Installing requirements for Web UI
Launching Web UI with arguments:
Error loading script: animation_v4.py
Traceback (most recent call last):
  File "C:\Users\gonzo_tower\Downloads\SD\SUPER SD 2.0\stable-diffusion-webui\modules\scripts.py", line 157, in load_scripts
    compiled = compile(text, scriptfile.path, 'exec')
  File "C:\Users\gonzo_tower\Downloads\SD\SUPER SD 2.0\stable-diffusion-webui\scripts\animation_v4.py", line 70
    <title>Animator/animation_v4.py at main · Animator-Anon/Animator · GitHub</title>
                                            ^
SyntaxError: invalid character '·' (U+00B7)
```

**Comment by bagolyszkij** [comment]
here is it:
[](https://drive.google.com/file/d/1-DW3cY0CuLfXk_LhYyJsHXvL4tTsksZf/view?usp=sharing)
many thanks for looking after mate! :)

**Comment by bagolyszkij** [comment]
https://drive.google.com/file/d/1-DW3cY0CuLfXk_LhYyJsHXvL4tTsksZf/view?usp=sharing

**Comment by bagolyszkij** [comment]
no probs
[animation_v4.zip](https://github.com/Animator-Anon/Animator/files/9869498/animation_v4.zip)

**Comment by Animator-Anon** [comment]
All good man, have fun!
