### ISSUE TITLE
Can you add install instructions please?

### ISSUE THREAD

**Issue by TheBitcoinBaron** [Animator-Anon/Animator#38]
I'm not a tech wizard, can you advise for noobs how to install this in automatic1111?

I tried moving the downloaded files into "stable-diffusion-webui\scripts\" and re running the program, but that doesnt work.

**Comment by TheBitcoinBaron** [comment]
I got it to show up but it will not work it gives this error:

Traceback (most recent call last):
  File "F:\STABLE_DIFF\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "F:\STABLE_DIFF\stable-diffusion-webui\webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "F:\STABLE_DIFF\stable-diffusion-webui\modules\img2img.py", line 137, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "F:\STABLE_DIFF\stable-diffusion-webui\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "F:\STABLE_DIFF\stable-diffusion-webui\scripts\animation_v6.py", line 369, in run
    os.mkdir(output_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'outputs/img2img-images\\20221124043026'

**Comment by TheBitcoinBaron** [comment]
Which isn't suprising, that directory doesn't exist.

**Comment by Animator-Anon** [comment]
I think this means parent folder doesn't exist. Do you have the paths configured correctly in webui?
If you run a normal img2img, without selecting my script, does this create an output?

I can adjust the code to recursively make folders, but this could end up being messy.

**Comment by TheBitcoinBaron** [comment]
I dont know because this is my first time trying img2img so I have no idea what I may be doing wrong.

**Comment by Northloop** [comment]
I was using the 0.7 version for quite some time and decided to update to check out some of the new features, specifically rotations. But now I'm pretty confused about the keyframe section. In 0.7 it was clear that I had seconds, denoise, zoom, x pan, y pan, positive prompt, negative prompt, and seed. But now, I'm pretty confused about how that section works. Like, how would it know that I'm not trying to pick different models. Or how would it know if I am? It doesn't appear to be something I can simply select the format on. How does it know which format I'm trying to use?

**Comment by Animator-Anon** [comment]
Everytime you generate an output with the script, it makes a subfolder with the date and time, and puts all of the images in there. keeps the main folder a bit tidier. In your case, I think it couldn't find the img2img folder. Running img2img by itself should have created it. Possibly check the settings page for paths and check they are valid.

**Comment by inck86** [comment]
I have errors when starting, I put the file in / scripts. Can you please explain how to set the animation?


Error loading script: animation.py
Traceback (most recent call last):
  File "C:\Automatic\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Automatic\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    compiled = compile(text, path, 'exec')
  File "C:\Automatic\stable-diffusion-webui\scripts\animation.py", line 73
    <title>Animator/animation.py at main · Animator-Anon/Animator</title>
                                         ^
SyntaxError: invalid character '·' (U+00B7)

Error loading script: animation_test.py
Traceback (most recent call last):
  File "C:\Automatic\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Automatic\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    compiled = compile(text, path, 'exec')
  File "C:\Automatic\stable-diffusion-webui\scripts\animation_test.py", line 73
    <title>Animator/animation_test.py at main · Animator-Anon/Animator</title>
                                              ^
SyntaxError: invalid character '·' (U+00B7)

Error loading script: animation_v6.py
Traceback (most recent call last):
  File "C:\Automatic\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Automatic\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    compiled = compile(text, path, 'exec')
  File "C:\Automatic\stable-diffusion-webui\scripts\animation_v6.py", line 73
    <title>Animator/animation_v6.py at main · Animator-Anon/Animator</title>
                                            ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by inck86** [comment]
> Download the zip file of the repository and extract the python file from that.

Yes, it helped, thanks!
